### ISSUE TITLE
add support for featured images

### ISSUE THREAD

**Issue by aschweigert** [INN/argo-links#1]
There seems to be some code in the original plugin for the bookmarklet to look for/import thumbnail images, let's revisit this and see if we can get it to work.

Ideal behavior would be to look for an open graph thumbnail image tag and if not found "suggest" images found in the content of the page being bookmarked.

If we can't get this to work, let's at least allow manual insertion of featured images and implement in the widget/post format.

**Comment by willhaynes** [comment]
Looks like there is an [open source php library](https://github.com/ramonztro/simple-scraper) for grabbing open graph tags (and other meta!).

[embed.ly](http://embed.ly/docs/explore/extract?url=http%3A%2F%2Ftechcrunch.com%2F2013%2F03%2F26%2Fembedly-now-goes-beyond-embedding-with-new-products-extract-display-for-making-sense-of-links-resizing-images%2F) also does a pretty good job at returning article metadata, and is [mostly free](http://embed.ly/pricing).

Have their been any thoughts up until now about what the best way to actually implement this is?

**Comment by aschweigert** [comment]
there's some garbage code already in the plugin (https://github.com/INN/argo-links/blob/master/argo-this.php#L108) that has never worked afaik. I'd like to not rely on embed.ly or some other third party service if we can avoid it, the php library might be worth exploring.

**Comment by willhaynes** [comment]
I think there's a general consensus that implementing your own DOM scraper is a great way to write code that never works. I'll look into the library and see how it works.

I presume we should also be downloading and caching local copies of these images (and not just hot linking), correct? I'll have to read up about starting potentially massive image downloads from unknown sources (I think there's [security concerns built into that too](http://stackoverflow.com/questions/8025236/is-it-possible-to-execute-php-with-extension-file-php-jpg)). Or maybe @rnagle has some input from his work on pmp?

**Comment by willhaynes** [comment]
I'll [throw a link to this](https://github.com/publicmediaplatform/pmp-wordpress/blob/codeception/inc/functions.php#L58) here after a discussion with Ryan. Some context for how PMP handles file downloads from URLs in WordPress.

**Comment by rnagle** [comment]
This is done though we don't actually show featured images anywhere. New ticket to determine how that should work is #35.
