### ISSUE TITLE
if link roundups are a collection of links, shouldn't they be...a collection of links?

### ISSUE THREAD

**Issue by aschweigert** [INN/argo-links#13]
Right now the link roundups are created by dumping the links (with description, etc.) directly into the body of a new post, instead maybe they ought to be more like "collections" (similar to how galleries are a collection of photos) where we preserve the reference to the original links, make them discrete, shareable units, etc.

**Comment by willhaynes** [comment]
This issue was moved to INN/link-roundups#3
