### ISSUE TITLE
link roundups are broken (in largo anyway)

### ISSUE THREAD

**Issue by aschweigert** [INN/argo-links#14]
I get a 404 when trying to view a post in the link roundup post type, probably because the largo single.php expects either a post or page but we'll need to dig into it a bit more to figure out how to handle these

**Comment by benlk** [comment]
There is an official, documented fix for this in the Argo docs: http://argoproject.org/argo-links.php

But we should try to fix this behavior anyways.

**Comment by benlk** [comment]
This is proving difficult to reproduce.

**Comment by benlk** [comment]
Ryan thinks that this can be automated:

> Go to Settings > Permalinks page in your WordPress dashboard and click the "save changes" button. Clicking the "save changes" button flushes WordPress' rewrite rules and fixes permalinks for custom post types.

But the trick will be catching the error condition.
