### ISSUE TITLE
Create read the docs page for the plugin?

### ISSUE THREAD

**Issue by rnagle** [INN/argo-links#17]
Can we pull any of the existing documentation from the Argo site?

What can we borrow from the read the docs set up for Largo?

**Comment by meredithinn** [comment]
ArgoLinks doc page http://argoproject.org/argo-links.php for reference.

**Comment by aschweigert** [comment]
I would say that we should at least have a more thorough readme here. Depending how complex things get, having end user docs on readthedocs might also be worthwhile (if the readme gets really long, etc.)

**Comment by benlk** [comment]
Docs set up here for the develop branch and master branch: https://argo-links.readthedocs.org/en/develop/

I'll merge develop into master when milestone 0.1 is done, and then it will be the main docs at https://argo-links.readthedocs.org/
