### ISSUE TITLE
push link roundups to mailchimp

### ISSUE THREAD

**Issue by aschweigert** [INN/argo-links#18]
This is a request from Midwest Energy News that I'd like to try to tackle as part of their redesign. Basically, assuming they use this plugin to curate links and make their morning roundup posts, they'd love a way to push that roundup directly to mailchimp in some format it would understand so that they would just have to proof it and then send it out to subscribers instead of having to copy and paste and do a bunch of manual work to get it moved over there.

**Comment by benlk** [comment]
Mailchimp [literally today](https://blog.mailchimp.com/announcing-mailchimp-api-v3-0/) launched their Version 3 API. It's not feature-complete, and supposedly the 2.x API will work.

It's not possible to create new campaigns with the current Version 3 Mailchimp API. [Campaign creation is a proposed feature](http://kb.mailchimp.com/api/article/3-roadmap).

- [ ] get list of templates from Mailchimp
    - possible in version 3: http://kb.mailchimp.com/api/resources/templates/templates-collection
    - possible in version 2: https://apidocs.mailchimp.com/api/2.0/#templates-methods
- [ ] create sane default email, save as draft
    - not possible in version 3
    - possible in version 2: https://apidocs.mailchimp.com/api/2.0/campaigns/create.php
- [ ] save API keys in WP settings

Mailchimp has some [best practices](http://kb.mailchimp.com/api/article/best-practices-for-api-3) for its API calls.

## Other ways

Mailchimp recommends some WordPress plugins. [There's one that does email creation from within WordPress](https://connect.mailchimp.com/integrations/integral-mailchimp-for-wordpress), but [it costs money](http://integralwp.com/plugins/complete-mailchimp-plugin-for-wordpress/).

**Comment by rnagle** [comment]
Created #27 to address the last checklist item in @benlk's comment.
