### ISSUE TITLE
Option to open links in a new tab/window

### ISSUE THREAD

**Issue by JamesPoundCSJ** [INN/argo-links#22]
It would be great to have the option to open links in a new tab/window, especially since they go off-site.

**Comment by benlk** [comment]
Do you think that opening in a new window should be the default behavior for links in the post roundups? (Is there a scenario where you would not want the links to open in a new tab or window?)

**Comment by aschweigert** [comment]
I'm generally pro-keeping things in the same window/tab but would be ok with this as an option configured in the plugin settings or something similar (as the default) and override-able for individual links.

**Comment by benlk** [comment]
For individual links, getting links to open in a new tab is as simple as adding `target="_blank"` in the post code editor, but a theme option hooked to a content filter would probably be best.

**Comment by aschweigert** [comment]
moved to https://github.com/INN/link-roundups/issues/30
