### ISSUE TITLE
It should be easy to tweet links as they are curated for Argo

### ISSUE THREAD

**Issue by AbeHandler** [INN/argo-links#26]
If a reporter has gone through the trouble of adding a link to Argo, then it should be very easy to send the link out on Twitter as well. The reporter should have the ability to tweet the link automatically (there would be a setting for this). That way the news organization can get the most out of (extremely limited) reporter time.

Argo Links would not necessarily need to be responsible for tweeting the links. It could simply export the links to a Buffer queue automatically (if Buffer has an API). Alternately, you could build an independent, external application that read from the XML feed of argo links and fed it into an auto Tweeting application.

@gabestein and I started working on something like this at The Lens but gave up once we lost our (excellent) news roundup writer. We modified the XML feed of Argo links to include a 140 character tweet that included a bitly version of the link. We wanted to include a character counter in the argolinks bookmarklet (on advice of @myersnews) but never got there.

We tried to get the links going out on Facebook as well but found that Facebook tended to bury posts that were added automatically with the API.

**Comment by JoeyColeman** [comment]
Great idea.

**Comment by aschweigert** [comment]
moved to https://github.com/INN/link-roundups/issues/27
