### ISSUE TITLE
If MailChimp campaign doesn't exist, remove "Edit in MailChimp" link from post editor

### ISSUE THREAD

**Issue by rnagle** [INN/argo-links#27]
If a campaign has been created via WordPress and deleted via MailChimp's dashboard, the "Edit..." link will still appear, but result in an error once you land on MailChimp.

For the time being, the workaround is to delete the `mc_web_id` custom field from the roundup post and reload the post editor page.

As for a solution, I know that I don't like the idea of checking the web id validity every time the post editor page loads. I'd rather intercept the click on the "Edit..." button and check the campaign at that point, delivering an error message to the user and handling removal of the `mc_web_id` automatically.

**Comment by kaeti** [comment]
This issue was moved to INN/link-roundups#15
