### ISSUE TITLE
Tell people to install the new "Argo Link This!" button

### ISSUE THREAD

**Issue by rnagle** [INN/argo-links#34]
After changing the way the plugin works in regard to the "Argo Link This!" button, we'll need to prevent users' existing "Link This!" buttons/links from leading to a 404 page.

Can probably just be a redirect to the "Argo Link This!" admin page and a notice to update their link.

**Comment by aschweigert** [comment]
+1 on a simple redirect plus admin notice, no further backwards compatibility seems necessary here to me

**Comment by rnagle** [comment]
@willhaynes figured out a way to make the old "Argo Link This!" button backwards compatible, so notices are necessary.

Just merged in his pull request. Cheers!
