### ISSUE TITLE
Submit to WP plugin directory

### ISSUE THREAD

**Issue by aschweigert** [INN/argo-links#4]

**Comment by aschweigert** [comment]
Let's also call this something other than argolinks. Credit the original creators in the readme similar to what documentcloud just did. But let's call it something more descriptive and likely to get it found/used when we submit it. Any ideas? @benlk @rnagle

**Comment by benlk** [comment]
Link Roundups (With MailChimp)

**Comment by benlk** [comment]
Do we have any suggestions for names other than "Argo Links"?

**Comment by benlk** [comment]
@willhaynes Were you working on a script or documentation on how to submit things to the WordPress plugin directory?

**Comment by willhaynes** [comment]
Yep. There's a script.

First though we need to [submit the plugin to the WordPress](https://wordpress.org/plugins/add/) to get an svn endpoint to push to.

That process involves submitting a name for the plugin. After this the name cannot change. The plugin will live at `wordpress.org/plugins/plugin-name` and `wp-content/plugins/plugin-name/`

With that, I think we should consider what we want this thing to be named. First, with the Argo project sunset, it could be confusing having "Argo" in an active product name. Second, "Argo Links" doesn't really say anything about what the plugin actually _does_, which I think is incredibly important to how people browse the plugin directory.

I don't have any great ideas on what to suggest instead, but I think that "Link Roundup" is generally more descriptive. We could replace Argo with Largo too, although I worry that might indicate that it requires Largo or a child theme (which I believe is not true).

@rnagle, @aschweigert thoughts? (@benlk too, if he has thoughts from the road)

**Comment by rnagle** [comment]
I agree a more descriptive name would be better. Maybe something like "Link Roundup Curator" or "Link Roundup Aggregator" -- something to indicate this is meant to help assemble a bunch of links from elsewhere on the interwebs for you to post on your site.

We can also add tags and such to the `readme.txt` we submit to wordpress.org. That should help the plugin find its way to folks that want to use it.

**Comment by aschweigert** [comment]
i think something like "link roundups" would probably be ok...i'll think about it a bit. we should definitely lose the argo prefix though and i'm not wild about using largo as a replacement. probably just stick with a more descriptive (and brief) name if possible.

**Comment by willhaynes** [comment]
Any additional thoughts here, @aschweigert @rnagle?

**Comment by aschweigert** [comment]
Link Roundup (or something similar) is fine with me

**Comment by willhaynes** [comment]
This issue was moved to INN/link-roundups#4
