### ISSUE TITLE
make sure single and archive templates for this post type behave as expected

### ISSUE THREAD

**Issue by aschweigert** [INN/argo-links#6]
there's a partial in largo (content-argolinks.php) for formatting these but that's probably not where it belongs, nor is it sufficient to ensure that the "single" view looks and behaves as one would expect, same for archive of argolinks/roundups.

**Comment by benlk** [comment]
I'm confused by this ticket?

**Comment by aschweigert** [comment]
i think it's probably not smart to have this template stuff in the theme, it should be in the plugin instead. So, if I view an archive page (archive.php) for the argolinks or argolinkroundups post types I should, in fact, get an archive page listing my saved links or published roundups. Similarly if I view a single post in either of those post types (single.php) I should get a post that displays what you'd expect as well (the link description, source, etc.) because right now I believe you either don't get a 404 or an empty post and that's not great. Does that kind of help? I might be able to explain better if I show you some examples.

**Comment by benlk** [comment]
Yes, that helps.

- [ ] partial for archive page of argolinks post types, possibly copied from Largo
- [ ] partial for archive page of argolinkroundups post types
- [ ] partial for single post of argolinks post type, possibly copied from Largo
- [ ] partial for single post of argolinkroundups post type

**Comment by rnagle** [comment]
I think we can use [template_include](https://codex.wordpress.org/Plugin_API/Filter_Reference/template_include) or [template_redirect](https://codex.wordpress.org/Plugin_API/Action_Reference/template_redirect) for this. Using one of these hooks should enable us able to override the templates if we ever have to.

**Comment by willhaynes** [comment]
It seems to be we're going to run into a lot of trouble overriding partials from a plugin. Would it not be enough to add a filter to the content/excerpt of these posts to return the proper content?

That way any DOM changes in a theme don't have to be duplicated in the plugin. Also, supporting themes other than Largo and Largo children is impossible if we're overriding its `content.php` dom.

**Comment by rnagle** [comment]
Just merged #31. That addresses the `argolinks` post type.

We'll also need something like #31 for the `argolinkroundups` post type, correct?

**Comment by willhaynes** [comment]
I don't believe so. Roundups are currently formatted with the with the standard `content.php` partial.

The main different is that roundups are stored with the DOM actually inserted into the post, where just links are stored with all their values in custom fields.

**Comment by aschweigert** [comment]
that seems right to me, let's test and doublec heck to make sure the linkroundup posts appear correctly in both contexts though (single and archive)

**Comment by willhaynes** [comment]
I did test pretty extensively on the default WordPress themes to make sure everything public was showing up right. Also did testing in Largo without templates (which we should remove eventually here when develop -> master).

Closing this for now.
